Added Combine support and updated model properties to camel case (#4)
rrainn/Lemmy-Swift-Client pull request #40
Opened 2023-12-08 19:30 UTC by colinfwalsh

Sorry for the previous PR, I should have read the Readme more thoroughly.

This might be a controversial PR, but I changed the script to automatically convert properties into camel case for the Codable models since that's the normal Swift convention.  All models have been updated to the latest version of the lemmy-js-client.

I also added Combine support in case others find that useful.

2023-12-08 21:25 UTC, fishcharlie requested changes
What Lemmy version did you use when updating the model properties?

2023-12-08 21:25 UTC, fishcharlie commented on autogen/index.js
> +}
Let's keep the formatting consistent, please use tabs here.

2023-12-08 21:25 UTC, fishcharlie commented on Sources/Lemmy-Swift-Client/Lemmy_Swift_Client.swift
> +}
This should be in a separate file.

2023-12-08 21:25 UTC, fishcharlie commented on autogen/index.js
> +                );
```suggestion
    let converted = str.toLowerCase().replace(/([-_][a-z])/g, (group) => {
        return group.toUpperCase().replace("-", "").replace("_", "");
    });
```

2023-12-08 23:25 UTC, colinfwalsh commented
> What Lemmy version did you use when updating the model properties?

v0.19-rc19

This version will definitely need a tagged release considering all the breaking changes.

In terms of the requested changes, those all look good.  I'll commit them as soon as I'm able.

2023-12-08 23:41 UTC, colinfwalsh commented
> > What Lemmy version did you use when updating the model properties?
> 
> v0.19-rc19
> 
> This version will definitely need a tagged release considering all the breaking changes.
> 
> In terms of the requested changes, those all look good. I'll commit them as soon as I'm able.

Changes committed - let me know if you have any other comments/suggestions.

Changes made

2023-12-09 01:55 UTC, fishcharlie commented
@colinfwalsh 

> v0.19-rc19

I don't think I wanna be using pre-release versions for this package. I'm open to conversation about this, but my initial instinct is to only use final versions.

2023-12-09 02:41 UTC, colinfwalsh commented
> @colinfwalsh
> 
> > v0.19-rc19
> 
> I don't think I wanna be using pre-release versions for this package. I'm open to conversation about this, but my initial instinct is to only use final versions.

I think that's valid. My only counter is that it shouldn't matter if versions are tagged.  For instance, the Readme could point users to using 3.0.3 but we'd still have 3.1.0 (as an example) for the upcoming 0.19 release.  Once 0.19 is found to be stable, we update the Readme etc.  I also want to note that 0.19 is due for release fairly soon - but I understand that's a weak argument.

At the end of the day, it's up to your discretion on how you'd like to handle things.

2023-12-09 02:46 UTC, colinfwalsh commented
I'd also like to advocate for a `develop` branch (or similar) that runs parallel to `main` for this exact scenario.

2023-12-28 20:12 UTC, colinfwalsh commented
Since v0.19 is officially supported and all requested changes are done, can we consider merging this or would you like to test this a bit further?  I updated all the models for the official v0.19 release as well.

2024-02-07 21:24 UTC, closed without merging